/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Tvqbl2oDV7M
 */
import ProductCard from "@/components/product-card";
import ProductHero from "@/components/product-hero";
import { products } from "@/lib/products";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center p-24">
      <div className="flex-col items-center justify-between max-w-5xl">
        <section className="flex w-full justify-center py-4 md:py-8 lg:py-12">
          <ProductHero product={products[0]} />
        </section>
        <section className="flex flex-col w-full justify-center py-12 space-y-4 md:py-24 lg:py-32 px-4 md:px-6">
          <h2 className="text-xl font-bold tracking-tighter sm:text-2xl md:text-3xl">
            Popular Products
          </h2>
          <div className="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <ProductCard product={products[1]} />
            <ProductCard product={products[2]} />
            <ProductCard product={products[3]} />
          </div>
        </section>
      </div>
    </main>
  );
}
